import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { motion } from 'framer-motion';

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main className={styles.main}>
            <motion.h1
               className={styles.title}
               initial={{ x: '-100rem' }}
               animate={{ x: 0 }}
               transition={{
                  type: 'spring',
                  duration: 1,
               }}
               // transition={{ delay: 1 }}
            >
               Hello
            </motion.h1>
            <motion.h1
               className={styles.title}
               initial={{ x: '100rem' }}
               animate={{ x: 0 }}
               transition={{
                  type: 'spring',
                  duration: 1,
               }}>
               World
            </motion.h1>

            <p className={styles.description}>
               Get started by editing{' '}
               <code className={styles.code}>pages/index.js</code>
            </p>

            <div className={styles.grid}>
               <motion.a
                  whileInView={{
                     x: ['-10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://nextjs.org/docs'
                  className={styles.card}>
                  <h2>Documentation &rarr;</h2>
                  <p>
                     Find in-depth information about Next.js features and API.
                  </p>
               </motion.a>

               <motion.a
                  whileInView={{
                     x: ['10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://nextjs.org/learn'
                  className={styles.card}>
                  <h2>Learn &rarr;</h2>
                  <p>
                     Learn about Next.js in an interactive course with quizzes!
                  </p>
               </motion.a>

               <motion.a
                  whileInView={{
                     x: ['-10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://github.com/vercel/next.js/tree/canary/examples'
                  className={styles.card}>
                  <h2>Examples &rarr;</h2>
                  <p>
                     Discover and deploy boilerplate example Next.js projects.
                  </p>
               </motion.a>

               <motion.a
                  whileInView={{
                     x: ['10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                  className={styles.card}>
                  <h2>Deploy &rarr;</h2>
                  <p>
                     Instantly deploy your Next.js site to a public URL with
                     Vercel.
                  </p>
               </motion.a>
               <motion.a
                  whileInView={{
                     x: ['-10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                  className={styles.card}>
                  <h2>Deploy &rarr;</h2>
                  <p>
                     Instantly deploy your Next.js site to a public URL with
                     Vercel.
                  </p>
               </motion.a>
               <motion.a
                  whileInView={{
                     x: ['10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                  className={styles.card}>
                  <h2>Deploy &rarr;</h2>
                  <p>
                     Instantly deploy your Next.js site to a public URL with
                     Vercel.
                  </p>
               </motion.a>
               <motion.a
                  whileInView={{
                     x: ['-10rem', '0rem', '0'],
                     transition: {
                        type: 'spring',
                        duration: 1,
                     },
                  }}
                  href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                  className={styles.card}>
                  <h2>Deploy &rarr;</h2>
                  <p>
                     Instantly deploy your Next.js site to a public URL with
                     Vercel.
                  </p>
               </motion.a>
            </div>
         </main>

         <footer className={styles.footer}>
            <a
               href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
               target='_blank'
               rel='noopener noreferrer'>
               Powered by{' '}
               <span className={styles.logo}>
                  <Image
                     src='/vercel.svg'
                     alt='Vercel Logo'
                     width={72}
                     height={16}
                  />
               </span>
            </a>
         </footer>
      </div>
   );
}
